CREATE DATABASE `TiendaUdem` /*!40100 COLLATE 'utf8_general_ci' */;
CREATE TABLE `Usuarios` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
ALTER TABLE `Usuarios`
	ADD COLUMN `Nombre` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `ID`;
ALTER TABLE `Usuarios`
	ADD COLUMN `Password` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `Nombre`;
ALTER TABLE `Usuarios`
	ADD COLUMN `Username` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `Password`;
CREATE TABLE `Insumos` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
ALTER TABLE `Insumos`
	ADD COLUMN `Nombre` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `ID`;
ALTER TABLE `Insumos`
	ADD COLUMN `Cantidad` INT NOT NULL DEFAULT '0' AFTER `Nombre`;
ALTER TABLE `Insumos`
	ADD COLUMN `Precio` DOUBLE NOT NULL DEFAULT '0' AFTER `Cantidad`;
ALTER TABLE `Insumos`
	ADD COLUMN `Tipo` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `Precio`;
CREATE TABLE `Producto` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `Producto` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
ALTER TABLE `Producto`
	ADD COLUMN `Nombre` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `ID`;
ALTER TABLE `Producto`
	ADD COLUMN `descripcion` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `Nombre`;
ALTER TABLE `Producto`
	ADD COLUMN `cantidad` INT NOT NULL DEFAULT '0' AFTER `descripcion`;
ALTER TABLE `Producto`
	ADD COLUMN `PrecioCompra` INT(11) NOT NULL DEFAULT '0' AFTER `cantidad`;
